version: '3.1'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  odoo:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  nginx:
    build: https://github.com/mtralla1/Erronka1.git
    volumes:
      - ./web_orrialdea:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80